### ISSUE TITLE
Typo in week 2 blog post

### ISSUE THREAD

**Issue by codesue** [hunter-college-ossd-spr19/msats5-weekly#2]
There's a typo in the first paragraph of the [week 2 blog post](https://github.com/hunter-college-ossd-spr19/msats5-weekly/blob/gh-pages/_posts/2019-02-08-week02.md):

"What should our **frist crontibutions** to an open source project look like?" should be "What should our **first contributions** to an open source project look like?"

**Comment by mgsats** [comment]
thanks for the heads up!
